In [1]:
import pandas as pd

In [5]:
d = pd.read_csv('feat_vec_1.csv', header=None)

In [6]:
d.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,255,255,255,89,89,89,89,255,255,255,...,255,255,255,255,255,255,255,255,255,1
1,255,255,255,104,104,104,104,255,255,255,...,255,255,255,255,255,255,255,255,255,1
2,255,255,255,99,99,99,99,255,255,255,...,255,255,255,255,255,255,255,255,255,1
3,255,255,255,207,207,207,207,255,255,255,...,255,255,255,255,255,255,255,255,255,1
4,255,255,255,109,109,109,109,255,255,255,...,255,255,255,255,255,255,255,255,255,1

In [7]:
cols = d.columns.tolist()
cols = cols[-1:] + cols[:-1]
cols

[49,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48]

In [8]:
df = d[cols]

In [9]:
df.to_csv('feat_vector_1_.csv', header=False, index=False)